name: Demo CI

on:
  repository_dispatch:
    types: [deploy-pages]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run Demo
      run: |
        echo "Deploying version: ${{ github.event.client_payload.version }}"
