name: Demo CI

on:
  repository_dispatch:
    types: [deploy-pages]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download release
      uses: robinraju/release-downloader@v1.11
      with:
        repository: ${{ github.event.client_payload.repository }}
        token: ${{ secrets.PAT_TOKEN }}
        tag: ${{ github.event.client_payload.version }}
        extract: true
        out-file-path: release

    - name: test
      run: |
        cd release
        ls -la
        cat build.txt
