name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Build
        run: |
          mkdir -p ./artifact
          echo build > ./artifact/build.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: build
          path: ./artifact

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
          path: artifact
          
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automatically generated release."
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifact/build.txt
          asset_name: build.txt
          asset_content_type: text/plain

      - name: Trigger deploy event
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{ "event_type": "trigger_event", "client_payload": { "version": "${{ github.ref_name }}" }}' \
            https://api.github.com/repos/minhtan143/github-actions-demo/dispatches
