name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Build
        run: |
          mkdir -p ./artifact
          echo build > ./artifact/build.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: build
          path: ./artifact

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
          path: artifact
          
      - name: Create Release
        uses: softprops/action-gh-release@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifact/build.txt

      - name: Trigger deploy event
        run: |
          curl --location 'https://api.github.com/repos/minhtan143/github-actions-demo/dispatches' \
            --header 'Content-Type: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.PAT_TOKEN }}' \
            --data '{
              "event_type": "deploy-pages",
              "client_payload": {
                "repository": "${{ github.repository }}",
                "version": "${{ github.ref_name }}"
              }
            }'
